### ISSUE TITLE
Closing incoming substreams

### ISSUE THREAD

**Issue by AljoschaMeyer** [dominictarr/packet-stream#11]
Is there anything preventing the following scenario?

1. A sends a stream packet with id 1 to B. A adds a Substream with id 1 to its outstreams.
2. B receives the stream packet with id 1. B adds a Substream with id -1 to its instreams.
3. A sends another stream packet with id 1 to B, i.e. the first piece of data of the stream.
4. B cancels the instream -1, that is B sends an end packet with id -1 to A. B then removes the Substream with id -1 from its instreams.
5. B now receives the second stream packet with id 1 sent by A. Since it removed the substream, it treats it as the creation of a new substream: B adds a Substream with id -1 to its instreams.
6. A now receives the end packet from B and removes the Substream with id 1 from its outstreams.

At the end of this sequence of events, B thinks there is an instream with id -1, but A has no outstream with id 1. Also, in step 5, A interprets a data packet as a stream-initialization packet. This creates no problem at the packet-stream level, but the consumer of the stream probably receives garbage.

**Comment by clehner** [comment]
On Thu, 31 Aug 2017 21:06 (UTC)
Aljoscha Meyer <notifications@github.com> wrote:

> Is there anything preventing the following scenario?
> 
> 1. A sends a stream packet with id 1 to B. A adds a Substream with id 1 to its outstreams.
> 2. B receives the stream packet with id 1. B adds a Substream with id -1 to its instreams.
> 3. A sends another stream packet with id 1 to B, i.e. the first piece of data of the stream.
> 4. B cancels the instream -1, that is B sends an end packet with id -1 to A. B then removes the Substream with id -1 from its instreams.

I think B should not remove the substream with id -1 from its instreams, until it gets an end packet from A for that substream.

> 5. B now receives the second stream packet with id 1 sent by A. Since it removed the substream, it treats it as the creation of a new substream: B adds a Substream with id -1 to its instreams.
> 6. A now receives the end packet from B and removes the Substream with id 1 from its outstreams.
> 
> At the end of this sequence of events, B thinks there is an instream with id -1, but A has no outstream with id 1. Also, in step 5, A interprets a data packet as a stream-initialization packet. This creates no problem at the packet-stream level, but the consumer of the stream probably receives garbage.

**Comment by AljoschaMeyer** [comment]
Thanks, looks like [this line](https://github.com/ssbc/packet-stream/blob/master/index.js#L223) performs exactly that check. Although it still feels somewhat weird to me that cancellation requires active cooperation of the peer.

An analogous check is done [for outstreams](https://github.com/ssbc/packet-stream/blob/master/index.js#L197) as well. I think one could get away without that check: The problematic packets (packets received after cancelling) have negative request ids and would simply be discarded since there is a) no handler but b) a negative rid never initiates a stream. In this case, cancellation can happen successfully even if the peer does not cooperate. Sending the end packet is simply a courtesy so that the peer can save some work.

**Comment by dominictarr** [comment]
the stream ids should increase monotonically, so another way is if the stream has been removed, and a new packet as lower than the expected next stream id (in this case, 2) then the receiver could just drop packets from the aborted stream. this would work because new a packet is sent as soon as the new stream is created. @clehner's suggestion also works.
