### ISSUE TITLE
Indicating closing of the whole PacketStream

### ISSUE THREAD

**Issue by AljoschaMeyer** [dominictarr/packet-stream#12]
A PacketStream signals its end by calling [`this.read(null, err || true)`](https://github.com/ssbc/packet-stream/blob/master/index.js#L110). The read method can than determine how to handle this: It might communicate this fact to the peer in an unspecified way, or it might do nothing.

Receiving end-of-stream happens if [packetstream.write(msg, end)](https://github.com/ssbc/packet-stream/blob/master/index.js#L133) is called with non-null `end`. When or whether to do this at all is again left to the implementor of `write`.

So in order to correctly deal with end-of-stream, an implementor must be aware of both the actual packet type (e.g. [packet-stream-codec](https://github.com/dominictarr/packet-stream-codec)) and the implementations of `read` and `write` (e.g somewhere in [muxrpc](https://github.com/ssbc/muxrpc) I guess?). This makes the PacketStream abstraction leaky: to detect end-of-stream, you need to look at a bunch of implementation details. I really like how the module is generic in the type of packets, but arbitrary end-of-stream signalling prevents full genericity. And it somewhat ties the whole thing to some parts of the ssb stack (packet-stream-codec and muxrpc).

A simple solution: signal end-of-packet-stream in-band via `this.read({req: 0, stream: false, end: true, value: null})`, i.e. by sending a message packet with the end flag set to true.

**Comment by clehner** [comment]
> So in order to correctly deal with end-of-stream, an implementor must be aware of both the actual packet type (e.g. [packet-stream-codec](https://github.com/dominictarr/packet-stream-codec)) and the implementations of `read` and `write` (e.g somewhere in [muxrpc](https://github.com/ssbc/muxrpc) I guess?). This makes the PacketStream abstraction leaky: to detect end-of-stream, you need to look at a bunch of implementation details. I really like how the module is generic in the type of packets, but arbitrary end-of-stream signalling prevents full genericity. And it somewhat ties the whole thing to some parts of the ssb stack (packet-stream-codec and muxrpc).

In this case I think the complexity is encapsulated by pull-goodbye [1] and packet-stream-codec's "goodbye packet". packet-stream-codec encodes end-of-stream as a zero'd packet header [3], and detects end-of-stream based on a packet header's length field being zero [3].

[1] https://github.com/dominictarr/pull-goodbye
[2] https://github.com/dominictarr/packet-stream-codec/blob/master/index.js#L22
[3] https://github.com/dominictarr/packet-stream-codec/blob/master/index.js#L100

> A simple solution: signal end-of-packet-stream in-band via `this.read({req: 0, stream: false, end: true, value: null})`, i.e. by sending a message packet with the end flag set to true.

Sounds okay, except it wouldn't be compatible with existing implementations - unless you encode it on the wire to match the current end-of-stream/goodbye packet.
From looking at the code, I think you you might be able to trigger this using `this.read('GOODBYE')` if you wanted to use packet-stream/packet-stream-codec without muxrpc.

So, I think pull-goodbye could be considered a thin layer of protocol between packet-stream and muxrpc. Are you concerned with making a compatible implementation of the protocols, or with packet-stream as a library/abstraction?

**Comment by AljoschaMeyer** [comment]
> Are you concerned with making a compatible implementation of the protocols, or with packet-stream as a library/abstraction?

Both. I'm [reimplementing](https://github.com/AljoschaMeyer/packet-stream-rs) packet-stream in rust. I want to use that for an ssb-client implementation, but also for some other projects. For those other projects, I'd prefer a clean abstraction, whereas I need the compatibility for ssb-related things.

I already sketched a slightly different multiplexing abstraction with the following key differences:

- packets which initiate a stream have a flag not shared by the follow-up packets of the stream (allows cancellation of incoming substreams without confirmation of the peer)
- end-packets have a flag to indicate whether they are a regular end or an error (packet-stream implicitely sends empty packets to indicate regular termination, again this is more of a convention than an actual part of the protocol)
- end-of-packet-stream as explained above. Any side would be able to cancel the whole stream (just as substreams have no half-open mode either (I think)).
- don't overload the meaning of the rid: just use unsigned 32 bit integers and a flag to indicate message vs request (same flag as used for beginning-of-stream vs content-of-stream)
- allow [request cancellation](https://github.com/AljoschaMeyer/packet-stream-rs#requests) (this can be added to packet-stream in a backwards-compatible way)

I prefer that abstraction, but I don't really want to create another protocol. Especially since I need to implement packet-stream anyways for the rust ssb stack.

- - -
Edit: I wrote down short description of the abstraction I'll implement if I end up ditching packet-stream: https://gist.github.com/AljoschaMeyer/597d06add3dd8e6b9136fa00268d48db

**Comment by AljoschaMeyer** [comment]
> packet-stream-codec encodes end-of-stream as a zero'd packet header [3], and detects end-of-stream based on a packet header's length field being zero [3].

That's not good 😞. It works fine, but only because packet-stream-codec does not support messages, only requests. A message would result in an empty header, except for the length field. But the length field is not in any way part of the packet-stream abstraction. So from the point of view of packet-stream, there would be no difference between messages and end-of-packet-stream. Looks like that makes it more complicated to support messages with the current codec, and perhaps impossible to write a compatible, fully generic implementation.

**Comment by clehner** [comment]
I have copied this discussion to SSB and responded there: %1nhEIWa0HOWytB2CK8sCi/yFGWS11CofMUXa6h1hJ+M=.sha256

**Comment by dominictarr** [comment]
@AljoschaMeyer we don't actually use messages for anything... so I think we can just consider that a misfeature and ignore it, not supported.

I'm interested in the changes you propose, are they backwards compatbile with this implementation? If it is, I'm onboard. If it's not, that is gonna be a pain
