### ISSUE TITLE
ps.destroy sends many packets

### ISSUE THREAD

**Issue by clehner** [dominictarr/packet-stream#6]
Calling ps.destroy triggers sending a packet for each open substream and request. This is problematic in the scuttlebot network where a peer rpc connection may have hundreds of open substreams. When the destroy method sends an error object, the stack trace gets sent repeatedly, once for each substream in either direction, which uses excessive bandwidth. Even if there is no stack trace, it still results in many packets getting sent for information which could be represented by one message.

I would like to make a way for packet-stream to use less bandwidth when ps.destroy is called. Here is how I am thinking to do this now:

- Have a special message type that means to send a message to all substreams.
- Have a way to advertise supporting this message type and detect that the other end supports it.
- On calling destroy: If the other end supports it, send the close message to all substreams with one packet. Otherwise, use the existing logic of calling destroy on all the substreams.

To preserve backwards compatibilty, the capability advertisement can be added as a new property onto an existing unrelated outgoing message (e.g. the first message sent by a substream). This is similar to [how git exchanges capabilities](https://www.kernel.org/pub/software/scm/git/docs/technical/protocol-capabilities.html): probably they had a similar situation, wanting to be able to upgrade the protocol while preserving compatibility.

@dominic, does this sound like an okay approach? Or do you have other ideas about how to deal with the underlying problem(s)?

**Comment by dominictarr** [comment]
Sending these packets was not my intention. I think that _destroy_ should just close the connection. The other side can then end all the streams with errors. _destroy_ should just kill the connection asap, but _close_ should abort the substreams...

Hmm, it's possible that destroy doesn't do that already, because of something that was needed to write tests that passed reliably, that is the sort of thing I'd do - but it's been a long time since I looked at this code, also

**Comment by clehner** [comment]
Ok, so then the error argument to *destroy* would still go to the local end of the substreams, but not be sent to the other ends. The close method would get the current behavior of *destroy*. Currently the close function "Marks the packetstream to close when all current IO is finished". Is there a use for such a method?

**Comment by clehner** [comment]
I looked for code paths leading to `ps.close`. It looks like muxrpc will only call this if `rpc.close(err)` is called with a falsy `err`. In scuttlebot, it looks like that only happens in the invite plugin when disconnecting from the pub after using an invite. So I think it might be okay to change `destroy` and `close` like you suggested. I'll try it and see what happens.

**Comment by clehner** [comment]
What I have now is a change to `destroy` to make it end the underlying stream without sending an end message to the substreams. `close` I'm leaving as is, since it isn't used much anyway. I also am making a change to handle the legacy case of end messages arriving for each substream, and destroy the underlying stream rather than wait for the rest of the end messages. (This is to save bandwidth and blocking of the event loop). I will make separate PRs for these
